# Generated by Django 5.2.1 on 2025-12-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_timestamp_contactmessage_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
