# Generated by Django 5.2.1 on 2026-03-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_submitted_at_contactmessage_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('mode', models.CharField(choices=[('Physical', 'Physical'), ('Online', 'Online')], max_length=20)),
                ('program', models.CharField(choices=[('launch', 'Office Launch'), ('pro', 'Professional Program'), ('fullstack', 'Full Stack'), ('extra', 'Full Stack Extra')], max_length=50)),
                ('depth', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('transfer', 'Transfer')], max_length=20)),
                ('transaction_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
