# Generated by Django 5.2.1 on 2026-03-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_programregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='programregistration',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
        migrations.AddField(
            model_name='programregistration',
            name='paystack_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
