# Generated by Django 5.2.1 on 2026-03-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_programregistration_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programregistration',
            old_name='paystack_ref',
            new_name='occupation',
        ),
        migrations.AddField(
            model_name='programregistration',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programregistration',
            name='aim',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programregistration',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programregistration',
            name='payment_method',
            field=models.CharField(choices=[('flutterwave', 'Flutterwave'), ('paystack', 'Paystack'), ('transfer', 'Transfer')], max_length=20),
        ),
    ]
